# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('WR', 'Working'), ('AW', 'Away'), ('OF', 'Offline'), ('DD', 'Do not disturb')], max_length=1)),
            ],
            options={
                'ordering': ('user_name',),
            },
        ),
    ]
